[package]
name = "bool_expr_parser_nom"
version = "0.1.7"
edition = "2021"

[lints.rust]
unsafe_code = "forbid"
unused = "allow"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = "z"

[dependencies]
nom = "7.1.3"
wasm-bindgen = "0.2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = "0.3"
